services:
  rtmp-server:
    build:
      context: ./rtmp-server
    container_name: rtmp-server
    restart: unless-stopped
    ports:
      - "1935:1935"
      - "8080:80"

  delay-streamer:
    build:
      context: ./delay-streamer
    container_name: delay-streamer
    restart: unless-stopped
    depends_on:
      - rtmp-server
    volumes:
      - ./delay-streamer:/app

  ui-api:
    build:
      context: ./ui-api
    container_name: ui-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./delay-streamer:/delay-streamer
